import { type LatLng } from "./geo";
import { INDIA_BOUNDS, INDIA_CENTER } from "./domain";

export interface StateInfo {
  id: string;
  name: string;
  type: "STATE" | "UT";
  capital: string;
  centroid: LatLng;
}

export interface DistrictInfo {
  id: string;
  name: string;
  state: string;
  headquarters: string;
  centroid: LatLng;
  polygon: LatLng[];
}

export interface MandalInfo {
  id: string;
  name: string;
  district: string;
  state: string;
  centroid: LatLng;
}

export interface PlaceInfo {
  id: string;
  name: string;
  district?: string;
  state: string;
  lat: number;
  lng: number;
  tier: 1 | 2 | 3 | 4; // 1: Mega/Capital, 2: District HQ, 3: Mandal/Town, 4: Village/Locality
  type: "city" | "town" | "mandal" | "village" | "port" | "island";
}

export interface RiverFeature {
  name: string;
  path: LatLng[];
}

export interface WaterBodyFeature {
  name: string;
  type: "lake" | "reservoir" | "bay" | "delta";
  center: LatLng;
  radiusKm: number;
}

/**
 * Geometric national boundary of the Republic of India.
 */
export const INDIA_NATIONAL_BOUNDARY: LatLng[] = [
  // North (Ladakh / Kashmir)
  { lat: 35.5, lng: 77.0 },
  { lat: 34.5, lng: 79.0 },
  { lat: 33.0, lng: 79.5 },
  // East Himachal & Uttarakhand
  { lat: 31.5, lng: 78.5 },
  { lat: 30.5, lng: 80.0 },
  // North-East / Sikkim / Arunachal Pradesh
  { lat: 27.8, lng: 88.5 },
  { lat: 28.5, lng: 94.0 },
  { lat: 28.2, lng: 96.5 },
  { lat: 27.0, lng: 96.8 },
  // Eastern border (Nagaland, Manipur, Mizoram)
  { lat: 25.5, lng: 95.0 },
  { lat: 24.0, lng: 93.5 },
  { lat: 22.5, lng: 93.0 },
  { lat: 21.8, lng: 92.5 },
  // Bay of Bengal / East Coast
  { lat: 21.6, lng: 89.0 }, // Sundarbans
  { lat: 20.8, lng: 87.0 }, // Odisha / Dhamra
  { lat: 19.8, lng: 85.8 }, // Puri
  { lat: 19.2, lng: 84.8 }, // Srikakulam border
  { lat: 17.7, lng: 83.3 }, // Visakhapatnam
  { lat: 16.9, lng: 82.2 }, // Kakinada
  { lat: 15.8, lng: 81.0 }, // Machilipatnam
  { lat: 15.5, lng: 80.0 }, // Ongole
  { lat: 14.4, lng: 80.1 }, // Nellore
  { lat: 13.1, lng: 80.3 }, // Chennai
  { lat: 11.9, lng: 79.8 }, // Puducherry
  { lat: 10.8, lng: 79.8 }, // Nagapattinam
  { lat: 9.3, lng: 79.1 }, // Rameswaram
  { lat: 8.1, lng: 77.5 }, // Kanyakumari (Southernmost mainland tip)
  // Arabian Sea / West Coast
  { lat: 8.5, lng: 76.9 }, // Thiruvananthapuram
  { lat: 9.9, lng: 76.2 }, // Kochi
  { lat: 11.2, lng: 75.8 }, // Kozhikode
  { lat: 12.9, lng: 74.8 }, // Mangaluru
  { lat: 15.3, lng: 73.8 }, // Goa
  { lat: 17.0, lng: 73.3 }, // Ratnagiri
  { lat: 19.0, lng: 72.8 }, // Mumbai
  { lat: 20.9, lng: 72.9 }, // Surat
  // Gujarat / Gulf of Khambhat & Kutch
  { lat: 21.7, lng: 72.2 }, // Bhavnagar
  { lat: 20.8, lng: 70.4 }, // Veraval
  { lat: 22.3, lng: 69.0 }, // Dwarka
  { lat: 23.0, lng: 68.6 }, // Kutch coast
  { lat: 23.8, lng: 68.8 }, // Sir Creek
  // Western border (Rajasthan, Punjab, J&K)
  { lat: 24.5, lng: 71.0 }, // Rann of Kutch
  { lat: 26.5, lng: 70.5 }, // Jaisalmer border
  { lat: 28.0, lng: 71.8 }, // Bikaner border
  { lat: 30.0, lng: 73.8 }, // Sri Ganganagar
  { lat: 31.6, lng: 74.8 }, // Amritsar / Attari
  { lat: 32.5, lng: 74.8 }, // Jammu border
  { lat: 34.0, lng: 74.0 }, // Line of Control (J&K)
  { lat: 35.5, lng: 77.0 }, // Back to Ladakh
];

/**
 * All 28 States and 8 Union Territories of India.
 */
export const INDIA_STATES: StateInfo[] = [
  {
    id: "AP",
    name: "Andhra Pradesh",
    type: "STATE",
    capital: "Amaravati",
    centroid: { lat: 15.9129, lng: 79.74 },
  },
  {
    id: "AR",
    name: "Arunachal Pradesh",
    type: "STATE",
    capital: "Itanagar",
    centroid: { lat: 28.218, lng: 94.7278 },
  },
  {
    id: "AS",
    name: "Assam",
    type: "STATE",
    capital: "Dispur",
    centroid: { lat: 26.2006, lng: 92.9376 },
  },
  {
    id: "BR",
    name: "Bihar",
    type: "STATE",
    capital: "Patna",
    centroid: { lat: 25.0961, lng: 85.3131 },
  },
  {
    id: "CG",
    name: "Chhattisgarh",
    type: "STATE",
    capital: "Raipur",
    centroid: { lat: 21.2787, lng: 81.8661 },
  },
  {
    id: "GA",
    name: "Goa",
    type: "STATE",
    capital: "Panaji",
    centroid: { lat: 15.2993, lng: 74.124 },
  },
  {
    id: "GJ",
    name: "Gujarat",
    type: "STATE",
    capital: "Gandhinagar",
    centroid: { lat: 22.2587, lng: 71.1924 },
  },
  {
    id: "HR",
    name: "Haryana",
    type: "STATE",
    capital: "Chandigarh",
    centroid: { lat: 29.0588, lng: 76.0856 },
  },
  {
    id: "HP",
    name: "Himachal Pradesh",
    type: "STATE",
    capital: "Shimla",
    centroid: { lat: 31.1048, lng: 77.1734 },
  },
  {
    id: "JH",
    name: "Jharkhand",
    type: "STATE",
    capital: "Ranchi",
    centroid: { lat: 23.6102, lng: 85.2799 },
  },
  {
    id: "KA",
    name: "Karnataka",
    type: "STATE",
    capital: "Bengaluru",
    centroid: { lat: 15.3173, lng: 75.7139 },
  },
  {
    id: "KL",
    name: "Kerala",
    type: "STATE",
    capital: "Thiruvananthapuram",
    centroid: { lat: 10.8505, lng: 76.2711 },
  },
  {
    id: "MP",
    name: "Madhya Pradesh",
    type: "STATE",
    capital: "Bhopal",
    centroid: { lat: 22.9734, lng: 78.6569 },
  },
  {
    id: "MH",
    name: "Maharashtra",
    type: "STATE",
    capital: "Mumbai",
    centroid: { lat: 19.7515, lng: 75.7139 },
  },
  {
    id: "MN",
    name: "Manipur",
    type: "STATE",
    capital: "Imphal",
    centroid: { lat: 24.6637, lng: 93.9063 },
  },
  {
    id: "ML",
    name: "Meghalaya",
    type: "STATE",
    capital: "Shillong",
    centroid: { lat: 25.467, lng: 91.3662 },
  },
  {
    id: "MZ",
    name: "Mizoram",
    type: "STATE",
    capital: "Aizawl",
    centroid: { lat: 23.1645, lng: 92.9376 },
  },
  {
    id: "NL",
    name: "Nagaland",
    type: "STATE",
    capital: "Kohima",
    centroid: { lat: 26.1584, lng: 94.5624 },
  },
  {
    id: "OD",
    name: "Odisha",
    type: "STATE",
    capital: "Bhubaneswar",
    centroid: { lat: 20.9517, lng: 85.0985 },
  },
  {
    id: "PB",
    name: "Punjab",
    type: "STATE",
    capital: "Chandigarh",
    centroid: { lat: 31.1471, lng: 75.3412 },
  },
  {
    id: "RJ",
    name: "Rajasthan",
    type: "STATE",
    capital: "Jaipur",
    centroid: { lat: 27.0238, lng: 74.2179 },
  },
  {
    id: "SK",
    name: "Sikkim",
    type: "STATE",
    capital: "Gangtok",
    centroid: { lat: 27.533, lng: 88.5122 },
  },
  {
    id: "TN",
    name: "Tamil Nadu",
    type: "STATE",
    capital: "Chennai",
    centroid: { lat: 11.1271, lng: 78.6569 },
  },
  {
    id: "TG",
    name: "Telangana",
    type: "STATE",
    capital: "Hyderabad",
    centroid: { lat: 18.1124, lng: 79.0193 },
  },
  {
    id: "TR",
    name: "Tripura",
    type: "STATE",
    capital: "Agartala",
    centroid: { lat: 23.9408, lng: 91.9882 },
  },
  {
    id: "UP",
    name: "Uttar Pradesh",
    type: "STATE",
    capital: "Lucknow",
    centroid: { lat: 26.8467, lng: 80.9462 },
  },
  {
    id: "UK",
    name: "Uttarakhand",
    type: "STATE",
    capital: "Dehradun",
    centroid: { lat: 30.0668, lng: 79.0193 },
  },
  {
    id: "WB",
    name: "West Bengal",
    type: "STATE",
    capital: "Kolkata",
    centroid: { lat: 22.9868, lng: 87.855 },
  },
  // Union Territories
  {
    id: "AN",
    name: "Andaman & Nicobar Islands",
    type: "UT",
    capital: "Port Blair",
    centroid: { lat: 11.7401, lng: 92.6586 },
  },
  {
    id: "CH",
    name: "Chandigarh",
    type: "UT",
    capital: "Chandigarh",
    centroid: { lat: 30.7333, lng: 76.7794 },
  },
  {
    id: "DH",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    type: "UT",
    capital: "Daman",
    centroid: { lat: 20.4283, lng: 72.8397 },
  },
  {
    id: "DL",
    name: "Delhi",
    type: "UT",
    capital: "New Delhi",
    centroid: { lat: 28.6139, lng: 77.209 },
  },
  {
    id: "JK",
    name: "Jammu & Kashmir",
    type: "UT",
    capital: "Srinagar / Jammu",
    centroid: { lat: 33.7782, lng: 76.5762 },
  },
  {
    id: "LA",
    name: "Ladakh",
    type: "UT",
    capital: "Leh",
    centroid: { lat: 34.1526, lng: 77.5771 },
  },
  {
    id: "LD",
    name: "Lakshadweep",
    type: "UT",
    capital: "Kavaratti",
    centroid: { lat: 10.5667, lng: 72.6417 },
  },
  {
    id: "PY",
    name: "Puducherry",
    type: "UT",
    capital: "Puducherry",
    centroid: { lat: 11.9416, lng: 79.8083 },
  },
];

/**
 * Authoritative dataset of all 26 districts of Andhra Pradesh with official boundaries.
 */
export const AP_DISTRICTS: DistrictInfo[] = [
  {
    id: "ap-srikakulam",
    name: "Srikakulam",
    state: "Andhra Pradesh",
    headquarters: "Srikakulam",
    centroid: { lat: 18.297, lng: 83.896 },
    polygon: [
      { lat: 19.15, lng: 84.75 },
      { lat: 18.85, lng: 84.45 },
      { lat: 18.3, lng: 83.9 },
      { lat: 18.2, lng: 83.6 },
      { lat: 18.7, lng: 83.75 },
      { lat: 19.15, lng: 84.75 },
    ],
  },
  {
    id: "ap-parvathipuram",
    name: "Parvathipuram Manyam",
    state: "Andhra Pradesh",
    headquarters: "Parvathipuram",
    centroid: { lat: 18.783, lng: 83.433 },
    polygon: [
      { lat: 19.0, lng: 83.6 },
      { lat: 18.75, lng: 83.7 },
      { lat: 18.6, lng: 83.3 },
      { lat: 18.85, lng: 83.2 },
      { lat: 19.0, lng: 83.6 },
    ],
  },
  {
    id: "ap-vizianagaram",
    name: "Vizianagaram",
    state: "Andhra Pradesh",
    headquarters: "Vizianagaram",
    centroid: { lat: 18.112, lng: 83.398 },
    polygon: [
      { lat: 18.4, lng: 83.6 },
      { lat: 18.05, lng: 83.55 },
      { lat: 17.95, lng: 83.2 },
      { lat: 18.35, lng: 83.15 },
      { lat: 18.4, lng: 83.6 },
    ],
  },
  {
    id: "ap-visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    headquarters: "Visakhapatnam",
    centroid: { lat: 17.6868, lng: 83.2185 },
    polygon: [
      { lat: 17.9, lng: 83.4 },
      { lat: 17.65, lng: 83.3 },
      { lat: 17.6, lng: 83.15 },
      { lat: 17.85, lng: 83.18 },
      { lat: 17.9, lng: 83.4 },
    ],
  },
  {
    id: "ap-alluri",
    name: "Alluri Sitharama Raju",
    state: "Andhra Pradesh",
    headquarters: "Paderu",
    centroid: { lat: 18.083, lng: 82.667 },
    polygon: [
      { lat: 18.5, lng: 83.1 },
      { lat: 17.8, lng: 82.8 },
      { lat: 17.4, lng: 81.6 },
      { lat: 18.1, lng: 82.2 },
      { lat: 18.5, lng: 83.1 },
    ],
  },
  {
    id: "ap-anakapalli",
    name: "Anakapalli",
    state: "Andhra Pradesh",
    headquarters: "Anakapalli",
    centroid: { lat: 17.69, lng: 83.003 },
    polygon: [
      { lat: 17.8, lng: 83.1 },
      { lat: 17.45, lng: 82.85 },
      { lat: 17.5, lng: 82.5 },
      { lat: 17.85, lng: 82.75 },
      { lat: 17.8, lng: 83.1 },
    ],
  },
  {
    id: "ap-kakinada",
    name: "Kakinada",
    state: "Andhra Pradesh",
    headquarters: "Kakinada",
    centroid: { lat: 16.989, lng: 82.247 },
    polygon: [
      { lat: 17.3, lng: 82.5 },
      { lat: 16.85, lng: 82.25 },
      { lat: 17.0, lng: 81.9 },
      { lat: 17.4, lng: 82.1 },
      { lat: 17.3, lng: 82.5 },
    ],
  },
  {
    id: "ap-eastgodavari",
    name: "East Godavari",
    state: "Andhra Pradesh",
    headquarters: "Rajahmundry",
    centroid: { lat: 17.005, lng: 81.777 },
    polygon: [
      { lat: 17.3, lng: 81.9 },
      { lat: 16.8, lng: 81.7 },
      { lat: 16.9, lng: 81.4 },
      { lat: 17.35, lng: 81.5 },
      { lat: 17.3, lng: 81.9 },
    ],
  },
  {
    id: "ap-konaseema",
    name: "Dr. B.R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    headquarters: "Amalapuram",
    centroid: { lat: 16.574, lng: 82.003 },
    polygon: [
      { lat: 16.85, lng: 82.1 },
      { lat: 16.4, lng: 81.9 },
      { lat: 16.45, lng: 81.65 },
      { lat: 16.8, lng: 81.75 },
      { lat: 16.85, lng: 82.1 },
    ],
  },
  {
    id: "ap-eluru",
    name: "Eluru",
    state: "Andhra Pradesh",
    headquarters: "Eluru",
    centroid: { lat: 16.71, lng: 81.1 },
    polygon: [
      { lat: 17.2, lng: 81.4 },
      { lat: 16.6, lng: 81.2 },
      { lat: 16.7, lng: 80.8 },
      { lat: 17.25, lng: 81.0 },
      { lat: 17.2, lng: 81.4 },
    ],
  },
  {
    id: "ap-westgodavari",
    name: "West Godavari",
    state: "Andhra Pradesh",
    headquarters: "Bhimavaram",
    centroid: { lat: 16.54, lng: 81.52 },
    polygon: [
      { lat: 16.8, lng: 81.6 },
      { lat: 16.35, lng: 81.65 },
      { lat: 16.45, lng: 81.35 },
      { lat: 16.75, lng: 81.4 },
      { lat: 16.8, lng: 81.6 },
    ],
  },
  {
    id: "ap-ntr",
    name: "NTR",
    state: "Andhra Pradesh",
    headquarters: "Vijayawada",
    centroid: { lat: 16.5062, lng: 80.648 },
    polygon: [
      { lat: 17.0, lng: 80.7 },
      { lat: 16.45, lng: 80.7 },
      { lat: 16.65, lng: 80.1 },
      { lat: 17.05, lng: 80.4 },
      { lat: 17.0, lng: 80.7 },
    ],
  },
  {
    id: "ap-krishna",
    name: "Krishna",
    state: "Andhra Pradesh",
    headquarters: "Machilipatnam",
    centroid: { lat: 16.18, lng: 81.13 },
    polygon: [
      { lat: 16.45, lng: 81.1 },
      { lat: 15.8, lng: 81.1 },
      { lat: 16.0, lng: 80.6 },
      { lat: 16.45, lng: 80.7 },
      { lat: 16.45, lng: 81.1 },
    ],
  },
  {
    id: "ap-palnadu",
    name: "Palnadu",
    state: "Andhra Pradesh",
    headquarters: "Narasaraopet",
    centroid: { lat: 16.234, lng: 80.05 },
    polygon: [
      { lat: 16.65, lng: 80.1 },
      { lat: 16.1, lng: 80.2 },
      { lat: 16.0, lng: 79.5 },
      { lat: 16.5, lng: 79.4 },
      { lat: 16.65, lng: 80.1 },
    ],
  },
  {
    id: "ap-guntur",
    name: "Guntur",
    state: "Andhra Pradesh",
    headquarters: "Guntur",
    centroid: { lat: 16.3067, lng: 80.4365 },
    polygon: [
      { lat: 16.5, lng: 80.6 },
      { lat: 16.15, lng: 80.55 },
      { lat: 16.2, lng: 80.25 },
      { lat: 16.45, lng: 80.35 },
      { lat: 16.5, lng: 80.6 },
    ],
  },
  {
    id: "ap-bapatla",
    name: "Bapatla",
    state: "Andhra Pradesh",
    headquarters: "Bapatla",
    centroid: { lat: 15.904, lng: 80.467 },
    polygon: [
      { lat: 16.15, lng: 80.6 },
      { lat: 15.65, lng: 80.4 },
      { lat: 15.8, lng: 80.0 },
      { lat: 16.1, lng: 80.2 },
      { lat: 16.15, lng: 80.6 },
    ],
  },
  {
    id: "ap-prakasam",
    name: "Prakasam",
    state: "Andhra Pradesh",
    headquarters: "Ongole",
    centroid: { lat: 15.505, lng: 80.049 },
    polygon: [
      { lat: 16.0, lng: 80.1 },
      { lat: 15.2, lng: 80.05 },
      { lat: 15.25, lng: 79.0 },
      { lat: 15.9, lng: 79.2 },
      { lat: 16.0, lng: 80.1 },
    ],
  },
  {
    id: "ap-nellore",
    name: "Sri Potti Sriramulu Nellore",
    state: "Andhra Pradesh",
    headquarters: "Nellore",
    centroid: { lat: 14.4426, lng: 79.9865 },
    polygon: [
      { lat: 15.1, lng: 80.1 },
      { lat: 13.8, lng: 80.1 },
      { lat: 14.1, lng: 79.4 },
      { lat: 15.0, lng: 79.5 },
      { lat: 15.1, lng: 80.1 },
    ],
  },
  {
    id: "ap-kurnool",
    name: "Kurnool",
    state: "Andhra Pradesh",
    headquarters: "Kurnool",
    centroid: { lat: 15.828, lng: 78.037 },
    polygon: [
      { lat: 16.0, lng: 78.1 },
      { lat: 15.4, lng: 78.0 },
      { lat: 15.5, lng: 77.2 },
      { lat: 15.95, lng: 77.35 },
      { lat: 16.0, lng: 78.1 },
    ],
  },
  {
    id: "ap-nandyal",
    name: "Nandyal",
    state: "Andhra Pradesh",
    headquarters: "Nandyal",
    centroid: { lat: 15.479, lng: 78.484 },
    polygon: [
      { lat: 16.1, lng: 78.8 },
      { lat: 15.1, lng: 78.6 },
      { lat: 15.2, lng: 78.0 },
      { lat: 15.9, lng: 78.2 },
      { lat: 16.1, lng: 78.8 },
    ],
  },
  {
    id: "ap-anantapur",
    name: "Ananthapuramu",
    state: "Andhra Pradesh",
    headquarters: "Anantapur",
    centroid: { lat: 14.682, lng: 77.601 },
    polygon: [
      { lat: 15.2, lng: 77.7 },
      { lat: 14.4, lng: 77.6 },
      { lat: 14.6, lng: 76.9 },
      { lat: 15.15, lng: 77.1 },
      { lat: 15.2, lng: 77.7 },
    ],
  },
  {
    id: "ap-srisathyasai",
    name: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    headquarters: "Puttaparthi",
    centroid: { lat: 14.167, lng: 77.812 },
    polygon: [
      { lat: 14.45, lng: 77.9 },
      { lat: 13.8, lng: 77.9 },
      { lat: 13.9, lng: 77.3 },
      { lat: 14.35, lng: 77.4 },
      { lat: 14.45, lng: 77.9 },
    ],
  },
  {
    id: "ap-kadapa",
    name: "YSR Kadapa",
    state: "Andhra Pradesh",
    headquarters: "Kadapa",
    centroid: { lat: 14.467, lng: 78.824 },
    polygon: [
      { lat: 15.1, lng: 78.8 },
      { lat: 14.2, lng: 78.9 },
      { lat: 14.25, lng: 78.2 },
      { lat: 14.9, lng: 78.3 },
      { lat: 15.1, lng: 78.8 },
    ],
  },
  {
    id: "ap-annamayya",
    name: "Annamayya",
    state: "Andhra Pradesh",
    headquarters: "Rayachoti",
    centroid: { lat: 14.054, lng: 78.752 },
    polygon: [
      { lat: 14.3, lng: 79.1 },
      { lat: 13.6, lng: 78.9 },
      { lat: 13.8, lng: 78.4 },
      { lat: 14.25, lng: 78.5 },
      { lat: 14.3, lng: 79.1 },
    ],
  },
  {
    id: "ap-chittoor",
    name: "Chittoor",
    state: "Andhra Pradesh",
    headquarters: "Chittoor",
    centroid: { lat: 13.217, lng: 79.1 },
    polygon: [
      { lat: 13.6, lng: 79.2 },
      { lat: 12.8, lng: 78.7 },
      { lat: 13.2, lng: 78.3 },
      { lat: 13.65, lng: 78.8 },
      { lat: 13.6, lng: 79.2 },
    ],
  },
  {
    id: "ap-tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    headquarters: "Tirupati",
    centroid: { lat: 13.6288, lng: 79.4192 },
    polygon: [
      { lat: 14.1, lng: 79.8 },
      { lat: 13.4, lng: 80.0 },
      { lat: 13.3, lng: 79.4 },
      { lat: 13.9, lng: 79.3 },
      { lat: 14.1, lng: 79.8 },
    ],
  },
];

/**
 * Major river systems of India.
 */
export const MAJOR_INDIAN_RIVERS: RiverFeature[] = [
  {
    name: "Ganga River",
    path: [
      { lat: 30.9, lng: 78.9 },
      { lat: 29.9, lng: 78.1 },
      { lat: 28.6, lng: 79.8 },
      { lat: 27.1, lng: 81.3 },
      { lat: 25.5, lng: 83.0 },
      { lat: 25.6, lng: 85.1 },
      { lat: 25.2, lng: 87.5 },
      { lat: 24.8, lng: 88.0 },
      { lat: 22.5, lng: 88.3 },
    ],
  },
  {
    name: "Yamuna River",
    path: [
      { lat: 31.0, lng: 78.4 },
      { lat: 30.4, lng: 77.6 },
      { lat: 28.7, lng: 77.2 },
      { lat: 27.2, lng: 78.0 },
      { lat: 25.5, lng: 81.8 },
    ],
  },
  {
    name: "Brahmaputra River",
    path: [
      { lat: 28.2, lng: 95.5 },
      { lat: 27.5, lng: 94.9 },
      { lat: 26.7, lng: 92.8 },
      { lat: 26.2, lng: 91.7 },
      { lat: 26.0, lng: 90.0 },
      { lat: 25.2, lng: 89.8 },
    ],
  },
  {
    name: "Godavari River",
    path: [
      { lat: 19.9, lng: 73.5 },
      { lat: 19.8, lng: 75.3 },
      { lat: 19.0, lng: 77.3 },
      { lat: 18.9, lng: 79.0 },
      { lat: 18.5, lng: 80.1 },
      { lat: 17.6, lng: 81.3 },
      { lat: 17.0, lng: 81.8 },
      { lat: 16.7, lng: 82.2 },
    ],
  },
  {
    name: "Krishna River",
    path: [
      { lat: 17.9, lng: 73.7 },
      { lat: 16.8, lng: 74.6 },
      { lat: 16.2, lng: 76.5 },
      { lat: 16.0, lng: 78.0 },
      { lat: 16.5, lng: 79.3 },
      { lat: 16.5, lng: 80.6 },
      { lat: 16.0, lng: 80.9 },
      { lat: 15.8, lng: 81.0 },
    ],
  },
  {
    name: "Narmada River",
    path: [
      { lat: 22.7, lng: 81.7 },
      { lat: 23.1, lng: 79.9 },
      { lat: 22.8, lng: 77.8 },
      { lat: 22.2, lng: 75.6 },
      { lat: 21.8, lng: 73.7 },
      { lat: 21.6, lng: 72.6 },
    ],
  },
  {
    name: "Mahanadi River",
    path: [
      { lat: 20.3, lng: 81.8 },
      { lat: 21.4, lng: 83.9 },
      { lat: 20.9, lng: 84.8 },
      { lat: 20.5, lng: 85.8 },
      { lat: 20.3, lng: 86.7 },
    ],
  },
  {
    name: "Kaveri River",
    path: [
      { lat: 12.4, lng: 75.7 },
      { lat: 12.3, lng: 76.6 },
      { lat: 12.1, lng: 77.8 },
      { lat: 11.4, lng: 78.5 },
      { lat: 10.8, lng: 79.8 },
    ],
  },
  {
    name: "Penna River",
    path: [
      { lat: 13.4, lng: 77.6 },
      { lat: 14.5, lng: 77.5 },
      { lat: 14.7, lng: 78.8 },
      { lat: 14.5, lng: 79.9 },
      { lat: 14.6, lng: 80.2 },
    ],
  },
  {
    name: "Tungabhadra River",
    path: [
      { lat: 14.0, lng: 75.7 },
      { lat: 15.3, lng: 76.5 },
      { lat: 15.9, lng: 77.4 },
      { lat: 16.0, lng: 78.1 },
    ],
  },
];

/**
 * Major Indian water bodies, lakes, and reservoirs.
 */
export const MAJOR_INDIAN_WATER_BODIES: WaterBodyFeature[] = [
  { name: "Chilika Lake", type: "lake", center: { lat: 19.7, lng: 85.3 }, radiusKm: 25 },
  { name: "Pulicat Lake", type: "lake", center: { lat: 13.68, lng: 80.15 }, radiusKm: 18 },
  { name: "Kolleru Lake", type: "lake", center: { lat: 16.65, lng: 81.33 }, radiusKm: 14 },
  { name: "Vembanad Lake", type: "lake", center: { lat: 9.6, lng: 76.4 }, radiusKm: 20 },
  { name: "Nagarjuna Sagar", type: "reservoir", center: { lat: 16.55, lng: 79.3 }, radiusKm: 15 },
  {
    name: "Srisailam Reservoir",
    type: "reservoir",
    center: { lat: 16.08, lng: 78.9 },
    radiusKm: 16,
  },
  { name: "Sardar Sarovar", type: "reservoir", center: { lat: 21.83, lng: 73.75 }, radiusKm: 22 },
  {
    name: "Gobind Sagar (Bhakra)",
    type: "reservoir",
    center: { lat: 31.4, lng: 76.4 },
    radiusKm: 18,
  },
  {
    name: "Hirakud Reservoir",
    type: "reservoir",
    center: { lat: 21.55, lng: 83.85 },
    radiusKm: 25,
  },
  { name: "Sambhar Salt Lake", type: "lake", center: { lat: 26.9, lng: 75.0 }, radiusKm: 16 },
  { name: "Wular Lake", type: "lake", center: { lat: 34.35, lng: 74.6 }, radiusKm: 12 },
  { name: "Loktak Lake", type: "lake", center: { lat: 24.55, lng: 93.8 }, radiusKm: 10 },
];

/**
 * Hierarchical places dataset across India.
 * Tier 1: Megacities & State Capitals
 * Tier 2: Major District Headquarters & Regional Cities
 * Tier 3: Mandals / Tehsils / Subdivisions & Major Towns
 * Tier 4: Key Localities & Villages
 */
export const INDIAN_PLACES: PlaceInfo[] = [
  // Tier 1: Megacities & State Capitals
  {
    id: "delhi",
    name: "New Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    tier: 1,
    type: "city",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    tier: 1,
    type: "city",
  },
  {
    id: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    tier: 1,
    type: "city",
  },
  {
    id: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    tier: 1,
    type: "city",
  },
  {
    id: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    tier: 1,
    type: "city",
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lng: 78.4867,
    tier: 1,
    type: "city",
  },
  {
    id: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    tier: 1,
    type: "city",
  },
  {
    id: "pune",
    name: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    tier: 1,
    type: "city",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    tier: 1,
    type: "city",
  },
  {
    id: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8467,
    lng: 80.9462,
    tier: 1,
    type: "city",
  },
  { id: "patna", name: "Patna", state: "Bihar", lat: 25.5941, lng: 85.1376, tier: 1, type: "city" },
  {
    id: "bhopal",
    name: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    tier: 1,
    type: "city",
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    state: "Chandigarh",
    lat: 30.7333,
    lng: 76.7794,
    tier: 1,
    type: "city",
  },
  {
    id: "thiruvananthapuram",
    name: "Thiruvananthapuram",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    tier: 1,
    type: "city",
  },
  {
    id: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    lat: 20.2961,
    lng: 85.8245,
    tier: 1,
    type: "city",
  },
  {
    id: "guwahati",
    name: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    tier: 1,
    type: "city",
  },
  {
    id: "srinagar",
    name: "Srinagar",
    state: "Jammu & Kashmir",
    lat: 34.0837,
    lng: 74.7973,
    tier: 1,
    type: "city",
  },
  {
    id: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    lat: 21.2514,
    lng: 81.6296,
    tier: 1,
    type: "city",
  },
  {
    id: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    lat: 23.3441,
    lng: 85.3096,
    tier: 1,
    type: "city",
  },
  {
    id: "dehradun",
    name: "Dehradun",
    state: "Uttarakhand",
    lat: 30.3165,
    lng: 78.0322,
    tier: 1,
    type: "city",
  },
  {
    id: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    lat: 31.1048,
    lng: 77.1734,
    tier: 1,
    type: "city",
  },
  { id: "panaji", name: "Panaji", state: "Goa", lat: 15.4909, lng: 73.8278, tier: 1, type: "city" },
  {
    id: "agartala",
    name: "Agartala",
    state: "Tripura",
    lat: 23.8315,
    lng: 91.2868,
    tier: 1,
    type: "city",
  },
  {
    id: "imphal",
    name: "Imphal",
    state: "Manipur",
    lat: 24.817,
    lng: 93.9368,
    tier: 1,
    type: "city",
  },
  {
    id: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    lat: 25.5788,
    lng: 91.8933,
    tier: 1,
    type: "city",
  },
  {
    id: "aizawl",
    name: "Aizawl",
    state: "Mizoram",
    lat: 23.7271,
    lng: 92.7176,
    tier: 1,
    type: "city",
  },
  {
    id: "kohima",
    name: "Kohima",
    state: "Nagaland",
    lat: 25.6751,
    lng: 94.1086,
    tier: 1,
    type: "city",
  },
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    lat: 27.3389,
    lng: 88.6065,
    tier: 1,
    type: "city",
  },
  {
    id: "itanagar",
    name: "Itanagar",
    state: "Arunachal Pradesh",
    lat: 27.0844,
    lng: 93.6053,
    tier: 1,
    type: "city",
  },
  {
    id: "portblair",
    name: "Port Blair",
    state: "Andaman & Nicobar Islands",
    lat: 11.6234,
    lng: 92.7265,
    tier: 1,
    type: "city",
  },

  // Andhra Pradesh Major Centers (Tier 1 & 2)
  {
    id: "visakhapatnam",
    name: "Visakhapatnam",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.6868,
    lng: 83.2185,
    tier: 1,
    type: "city",
  },
  {
    id: "vijayawada",
    name: "Vijayawada",
    district: "NTR",
    state: "Andhra Pradesh",
    lat: 16.5062,
    lng: 80.648,
    tier: 1,
    type: "city",
  },
  {
    id: "amaravati",
    name: "Amaravati",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.5131,
    lng: 80.5165,
    tier: 1,
    type: "city",
  },
  {
    id: "guntur",
    name: "Guntur",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.3067,
    lng: 80.4365,
    tier: 2,
    type: "city",
  },
  {
    id: "tirupati",
    name: "Tirupati",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 13.6288,
    lng: 79.4192,
    tier: 2,
    type: "city",
  },
  {
    id: "kurnool",
    name: "Kurnool",
    district: "Kurnool",
    state: "Andhra Pradesh",
    lat: 15.8281,
    lng: 78.0373,
    tier: 2,
    type: "city",
  },
  {
    id: "nellore",
    name: "Nellore",
    district: "Nellore",
    state: "Andhra Pradesh",
    lat: 14.4426,
    lng: 79.9865,
    tier: 2,
    type: "city",
  },
  {
    id: "rajahmundry",
    name: "Rajahmundry",
    district: "East Godavari",
    state: "Andhra Pradesh",
    lat: 17.0005,
    lng: 81.804,
    tier: 2,
    type: "city",
  },
  {
    id: "kakinada",
    name: "Kakinada",
    district: "Kakinada",
    state: "Andhra Pradesh",
    lat: 16.9891,
    lng: 82.2475,
    tier: 2,
    type: "city",
  },
  {
    id: "kadapa",
    name: "Kadapa",
    district: "YSR Kadapa",
    state: "Andhra Pradesh",
    lat: 14.4674,
    lng: 78.8241,
    tier: 2,
    type: "city",
  },
  {
    id: "anantapur",
    name: "Anantapur",
    district: "Ananthapuramu",
    state: "Andhra Pradesh",
    lat: 14.6819,
    lng: 77.6006,
    tier: 2,
    type: "city",
  },
  {
    id: "vizianagaram",
    name: "Vizianagaram",
    district: "Vizianagaram",
    state: "Andhra Pradesh",
    lat: 18.1067,
    lng: 83.3956,
    tier: 2,
    type: "city",
  },
  {
    id: "srikakulam",
    name: "Srikakulam",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    lat: 18.297,
    lng: 83.896,
    tier: 2,
    type: "city",
  },
  {
    id: "eluru",
    name: "Eluru",
    district: "Eluru",
    state: "Andhra Pradesh",
    lat: 16.7107,
    lng: 81.0952,
    tier: 2,
    type: "city",
  },
  {
    id: "ongole",
    name: "Ongole",
    district: "Prakasam",
    state: "Andhra Pradesh",
    lat: 15.5057,
    lng: 80.0499,
    tier: 2,
    type: "city",
  },
  {
    id: "machilipatnam",
    name: "Machilipatnam",
    district: "Krishna",
    state: "Andhra Pradesh",
    lat: 16.1875,
    lng: 81.1389,
    tier: 2,
    type: "city",
  },
  {
    id: "chittoor",
    name: "Chittoor",
    district: "Chittoor",
    state: "Andhra Pradesh",
    lat: 13.2172,
    lng: 79.1003,
    tier: 2,
    type: "city",
  },
  {
    id: "nandyal",
    name: "Nandyal",
    district: "Nandyal",
    state: "Andhra Pradesh",
    lat: 15.479,
    lng: 78.484,
    tier: 2,
    type: "city",
  },
  {
    id: "hindupur",
    name: "Hindupur",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    lat: 13.829,
    lng: 77.492,
    tier: 2,
    type: "city",
  },

  // Tier 3: Mandals, Tehsils, Subdivisions, & Coastal Ports
  {
    id: "anakapalle_m",
    name: "Anakapalle",
    district: "Anakapalli",
    state: "Andhra Pradesh",
    lat: 17.69,
    lng: 83.003,
    tier: 3,
    type: "mandal",
  },
  {
    id: "bheemunipatnam",
    name: "Bheemunipatnam",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.89,
    lng: 83.45,
    tier: 3,
    type: "town",
  },
  {
    id: "araku",
    name: "Araku Valley",
    district: "Alluri Sitharama Raju",
    state: "Andhra Pradesh",
    lat: 18.327,
    lng: 82.881,
    tier: 3,
    type: "town",
  },
  {
    id: "paderu",
    name: "Paderu",
    district: "Alluri Sitharama Raju",
    state: "Andhra Pradesh",
    lat: 18.083,
    lng: 82.667,
    tier: 3,
    type: "mandal",
  },
  {
    id: "parvathipuram",
    name: "Parvathipuram",
    district: "Parvathipuram Manyam",
    state: "Andhra Pradesh",
    lat: 18.783,
    lng: 83.433,
    tier: 3,
    type: "town",
  },
  {
    id: "bobbili",
    name: "Bobbili",
    district: "Vizianagaram",
    state: "Andhra Pradesh",
    lat: 18.57,
    lng: 83.36,
    tier: 3,
    type: "mandal",
  },
  {
    id: "salur",
    name: "Salur",
    district: "Parvathipuram Manyam",
    state: "Andhra Pradesh",
    lat: 18.52,
    lng: 83.21,
    tier: 3,
    type: "mandal",
  },
  {
    id: "tekkali",
    name: "Tekkali",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    lat: 18.61,
    lng: 84.23,
    tier: 3,
    type: "mandal",
  },
  {
    id: "palasa",
    name: "Palasa Kasibugga",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    lat: 18.77,
    lng: 84.41,
    tier: 3,
    type: "town",
  },
  {
    id: "sompeta",
    name: "Sompeta",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    lat: 18.93,
    lng: 84.59,
    tier: 3,
    type: "mandal",
  },
  {
    id: "ichchapuram",
    name: "Ichchapuram",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    lat: 19.11,
    lng: 84.69,
    tier: 3,
    type: "town",
  },
  {
    id: "tuni",
    name: "Tuni",
    district: "Kakinada",
    state: "Andhra Pradesh",
    lat: 17.35,
    lng: 82.55,
    tier: 3,
    type: "town",
  },
  {
    id: "pithapuram",
    name: "Pithapuram",
    district: "Kakinada",
    state: "Andhra Pradesh",
    lat: 17.11,
    lng: 82.26,
    tier: 3,
    type: "mandal",
  },
  {
    id: "samalkot",
    name: "Samalkot",
    district: "Kakinada",
    state: "Andhra Pradesh",
    lat: 17.05,
    lng: 82.17,
    tier: 3,
    type: "town",
  },
  {
    id: "amalapuram",
    name: "Amalapuram",
    district: "Dr. B.R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    lat: 16.574,
    lng: 82.003,
    tier: 3,
    type: "town",
  },
  {
    id: "razole",
    name: "Razole",
    district: "Dr. B.R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    lat: 16.45,
    lng: 81.83,
    tier: 3,
    type: "mandal",
  },
  {
    id: "narasapuram",
    name: "Narasapuram",
    district: "West Godavari",
    state: "Andhra Pradesh",
    lat: 16.44,
    lng: 81.7,
    tier: 3,
    type: "port",
  },
  {
    id: "bhimavaram",
    name: "Bhimavaram",
    district: "West Godavari",
    state: "Andhra Pradesh",
    lat: 16.54,
    lng: 81.52,
    tier: 3,
    type: "town",
  },
  {
    id: "tadepalligudem",
    name: "Tadepalligudem",
    district: "West Godavari",
    state: "Andhra Pradesh",
    lat: 16.81,
    lng: 81.53,
    tier: 3,
    type: "town",
  },
  {
    id: "tanuku",
    name: "Tanuku",
    district: "West Godavari",
    state: "Andhra Pradesh",
    lat: 16.75,
    lng: 81.68,
    tier: 3,
    type: "town",
  },
  {
    id: "jangareddygudem",
    name: "Jangareddygudem",
    district: "Eluru",
    state: "Andhra Pradesh",
    lat: 17.12,
    lng: 81.29,
    tier: 3,
    type: "town",
  },
  {
    id: "nuzvid",
    name: "Nuzvid",
    district: "Eluru",
    state: "Andhra Pradesh",
    lat: 16.78,
    lng: 80.85,
    tier: 3,
    type: "town",
  },
  {
    id: "gudivada",
    name: "Gudivada",
    district: "Krishna",
    state: "Andhra Pradesh",
    lat: 16.44,
    lng: 80.99,
    tier: 3,
    type: "town",
  },
  {
    id: "vuyyuru",
    name: "Vuyyuru",
    district: "Krishna",
    state: "Andhra Pradesh",
    lat: 16.37,
    lng: 80.84,
    tier: 3,
    type: "mandal",
  },
  {
    id: "avanigadda",
    name: "Avanigadda",
    district: "Krishna",
    state: "Andhra Pradesh",
    lat: 16.02,
    lng: 80.92,
    tier: 3,
    type: "mandal",
  },
  {
    id: "jaggayyapeta",
    name: "Jaggayyapeta",
    district: "NTR",
    state: "Andhra Pradesh",
    lat: 16.89,
    lng: 80.09,
    tier: 3,
    type: "town",
  },
  {
    id: "nandigama",
    name: "Nandigama",
    district: "NTR",
    state: "Andhra Pradesh",
    lat: 16.77,
    lng: 80.29,
    tier: 3,
    type: "town",
  },
  {
    id: "tiruvuru",
    name: "Tiruvuru",
    district: "NTR",
    state: "Andhra Pradesh",
    lat: 17.11,
    lng: 80.61,
    tier: 3,
    type: "mandal",
  },
  {
    id: "tenali",
    name: "Tenali",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.24,
    lng: 80.64,
    tier: 3,
    type: "town",
  },
  {
    id: "mangalagiri",
    name: "Mangalagiri",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.43,
    lng: 80.56,
    tier: 3,
    type: "town",
  },
  {
    id: "ponnur",
    name: "Ponnur",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.07,
    lng: 80.56,
    tier: 3,
    type: "mandal",
  },
  {
    id: "narasaraopet",
    name: "Narasaraopet",
    district: "Palnadu",
    state: "Andhra Pradesh",
    lat: 16.234,
    lng: 80.05,
    tier: 3,
    type: "town",
  },
  {
    id: "sattenapalle",
    name: "Sattenapalle",
    district: "Palnadu",
    state: "Andhra Pradesh",
    lat: 16.39,
    lng: 80.18,
    tier: 3,
    type: "town",
  },
  {
    id: "vinukonda",
    name: "Vinukonda",
    district: "Palnadu",
    state: "Andhra Pradesh",
    lat: 16.05,
    lng: 79.74,
    tier: 3,
    type: "town",
  },
  {
    id: "chirala",
    name: "Chirala",
    district: "Bapatla",
    state: "Andhra Pradesh",
    lat: 15.82,
    lng: 80.35,
    tier: 3,
    type: "town",
  },
  {
    id: "bapatla_t",
    name: "Bapatla",
    district: "Bapatla",
    state: "Andhra Pradesh",
    lat: 15.904,
    lng: 80.467,
    tier: 3,
    type: "town",
  },
  {
    id: "repalle",
    name: "Repalle",
    district: "Bapatla",
    state: "Andhra Pradesh",
    lat: 16.02,
    lng: 80.83,
    tier: 3,
    type: "town",
  },
  {
    id: "markapur",
    name: "Markapur",
    district: "Prakasam",
    state: "Andhra Pradesh",
    lat: 15.735,
    lng: 79.278,
    tier: 3,
    type: "town",
  },
  {
    id: "kandukur",
    name: "Kandukur",
    district: "Nellore",
    state: "Andhra Pradesh",
    lat: 15.21,
    lng: 79.9,
    tier: 3,
    type: "town",
  },
  {
    id: "kavali",
    name: "Kavali",
    district: "Nellore",
    state: "Andhra Pradesh",
    lat: 14.91,
    lng: 79.99,
    tier: 3,
    type: "town",
  },
  {
    id: "gudur",
    name: "Gudur",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 14.15,
    lng: 79.85,
    tier: 3,
    type: "town",
  },
  {
    id: "sullurpeta",
    name: "Sullurpeta",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 13.7,
    lng: 80.02,
    tier: 3,
    type: "town",
  },
  {
    id: "sriharikota",
    name: "Sriharikota (ISRO)",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 13.72,
    lng: 80.2,
    tier: 3,
    type: "island",
  },
  {
    id: "srikalahasti",
    name: "Srikalahasti",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 13.75,
    lng: 79.7,
    tier: 3,
    type: "town",
  },
  {
    id: "madanapalle",
    name: "Madanapalle",
    district: "Annamayya",
    state: "Andhra Pradesh",
    lat: 13.55,
    lng: 78.5,
    tier: 3,
    type: "town",
  },
  {
    id: "rayachoti",
    name: "Rayachoti",
    district: "Annamayya",
    state: "Andhra Pradesh",
    lat: 14.054,
    lng: 78.752,
    tier: 3,
    type: "town",
  },
  {
    id: "rajampet",
    name: "Rajampet",
    district: "Annamayya",
    state: "Andhra Pradesh",
    lat: 14.19,
    lng: 79.16,
    tier: 3,
    type: "town",
  },
  {
    id: "proddatur",
    name: "Proddatur",
    district: "YSR Kadapa",
    state: "Andhra Pradesh",
    lat: 14.75,
    lng: 78.55,
    tier: 3,
    type: "town",
  },
  {
    id: "pulivendula",
    name: "Pulivendula",
    district: "YSR Kadapa",
    state: "Andhra Pradesh",
    lat: 14.42,
    lng: 78.23,
    tier: 3,
    type: "town",
  },
  {
    id: "dhone",
    name: "Dhone",
    district: "Nandyal",
    state: "Andhra Pradesh",
    lat: 15.421,
    lng: 77.872,
    tier: 3,
    type: "town",
  },
  {
    id: "adoni",
    name: "Adoni",
    district: "Kurnool",
    state: "Andhra Pradesh",
    lat: 15.63,
    lng: 77.27,
    tier: 3,
    type: "town",
  },
  {
    id: "guntakal",
    name: "Guntakal",
    district: "Ananthapuramu",
    state: "Andhra Pradesh",
    lat: 15.17,
    lng: 77.37,
    tier: 3,
    type: "town",
  },
  {
    id: "dharmavaram",
    name: "Dharmavaram",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    lat: 14.412,
    lng: 77.721,
    tier: 3,
    type: "town",
  },
  {
    id: "puttaparthi",
    name: "Puttaparthi",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    lat: 14.167,
    lng: 77.812,
    tier: 3,
    type: "town",
  },
  {
    id: "kadiri",
    name: "Kadiri",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    lat: 14.11,
    lng: 78.16,
    tier: 3,
    type: "town",
  },
  {
    id: "kuppam",
    name: "Kuppam",
    district: "Chittoor",
    state: "Andhra Pradesh",
    lat: 12.75,
    lng: 78.36,
    tier: 3,
    type: "town",
  },
  {
    id: "palamaner",
    name: "Palamaner",
    district: "Chittoor",
    state: "Andhra Pradesh",
    lat: 13.2,
    lng: 78.75,
    tier: 3,
    type: "town",
  },
];

/**
 * Backward-compatible aliases for legacy Andhra Pradesh mapping modules.
 */
export const AP_STATE_BOUNDARY = INDIA_NATIONAL_BOUNDARY;
export const AP_CITIES = INDIAN_PLACES.filter((p) => p.state === "Andhra Pradesh");
export const AP_RIVERS = MAJOR_INDIAN_RIVERS.filter(
  (r) =>
    r.name.includes("Krishna") ||
    r.name.includes("Godavari") ||
    r.name.includes("Penna") ||
    r.name.includes("Tungabhadra"),
);
