import { type LatLng, haversineKm } from "./geo";

export interface RoadNode {
  id: string;
  name: string;
  district: string;
  lat: number;
  lng: number;
  isHighwayJunction: boolean;
}

export interface RoadSegment {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  roadName: string;
  roadType: "NATIONAL_HIGHWAY" | "STATE_HIGHWAY" | "ARTERIAL" | "CONNECTING";
  distanceKm: number;
  speedLimitKmh: number;
  path: LatLng[];
}

/**
 * Nodes representing major junctions, city connections, and highway intersections across Andhra Pradesh.
 */
export const AP_ROAD_NODES: RoadNode[] = [
  // NH16 Coastal Backbone (North to South)
  {
    id: "node-ichchapuram",
    name: "Ichchapuram (NH16)",
    district: "Srikakulam",
    lat: 19.116,
    lng: 84.693,
    isHighwayJunction: true,
  },
  {
    id: "node-sompeta",
    name: "Sompeta (NH16)",
    district: "Srikakulam",
    lat: 18.932,
    lng: 84.588,
    isHighwayJunction: true,
  },
  {
    id: "node-tekkali",
    name: "Tekkali (NH16)",
    district: "Srikakulam",
    lat: 18.614,
    lng: 84.237,
    isHighwayJunction: true,
  },
  {
    id: "node-narasannapeta",
    name: "Narasannapeta (NH16)",
    district: "Srikakulam",
    lat: 18.423,
    lng: 84.045,
    isHighwayJunction: true,
  },
  {
    id: "node-srikakulam",
    name: "Srikakulam Central (NH16)",
    district: "Srikakulam",
    lat: 18.297,
    lng: 83.897,
    isHighwayJunction: true,
  },
  {
    id: "node-ranasthalam",
    name: "Ranasthalam (NH16)",
    district: "Srikakulam",
    lat: 18.216,
    lng: 83.673,
    isHighwayJunction: false,
  },
  {
    id: "node-vizianagaram",
    name: "Vizianagaram Bypass (NH16/NH26)",
    district: "Vizianagaram",
    lat: 18.112,
    lng: 83.398,
    isHighwayJunction: true,
  },
  {
    id: "node-tagarapuvalasa",
    name: "Tagarapuvalasa (NH16)",
    district: "Visakhapatnam",
    lat: 17.935,
    lng: 83.432,
    isHighwayJunction: true,
  },
  {
    id: "node-anandapuram",
    name: "Anandapuram Junction (NH16)",
    district: "Visakhapatnam",
    lat: 17.908,
    lng: 83.376,
    isHighwayJunction: true,
  },
  {
    id: "node-madhurawada",
    name: "Madhurawada (NH16)",
    district: "Visakhapatnam",
    lat: 17.808,
    lng: 83.355,
    isHighwayJunction: false,
  },
  {
    id: "node-visakhapatnam",
    name: "Visakhapatnam City Central",
    district: "Visakhapatnam",
    lat: 17.687,
    lng: 83.218,
    isHighwayJunction: true,
  },
  {
    id: "node-gajuwaka",
    name: "Gajuwaka Industrial Hub (NH16)",
    district: "Visakhapatnam",
    lat: 17.698,
    lng: 83.189,
    isHighwayJunction: true,
  },
  {
    id: "node-kurmannapalem",
    name: "Kurmannapalem Steel Plant (NH16)",
    district: "Visakhapatnam",
    lat: 17.678,
    lng: 83.145,
    isHighwayJunction: true,
  },
  {
    id: "node-anakapalli",
    name: "Anakapalli Bypass (NH16)",
    district: "Anakapalli",
    lat: 17.69,
    lng: 83.003,
    isHighwayJunction: true,
  },
  {
    id: "node-yelamanchili",
    name: "Yelamanchili (NH16)",
    district: "Anakapalli",
    lat: 17.552,
    lng: 82.862,
    isHighwayJunction: false,
  },
  {
    id: "node-nakapalli",
    name: "Nakkapalli (NH16)",
    district: "Anakapalli",
    lat: 17.432,
    lng: 82.721,
    isHighwayJunction: false,
  },
  {
    id: "node-payakaraopeta",
    name: "Payakaraopeta (NH16)",
    district: "Anakapalli",
    lat: 17.362,
    lng: 82.571,
    isHighwayJunction: true,
  },
  {
    id: "node-tuni",
    name: "Tuni (NH16)",
    district: "Kakinada",
    lat: 17.354,
    lng: 82.548,
    isHighwayJunction: true,
  },
  {
    id: "node-annavaram",
    name: "Annavaram (NH16)",
    district: "Kakinada",
    lat: 17.283,
    lng: 82.404,
    isHighwayJunction: false,
  },
  {
    id: "node-kathipudi",
    name: "Kathipudi Junction (NH16/NH216)",
    district: "Kakinada",
    lat: 17.241,
    lng: 82.339,
    isHighwayJunction: true,
  },
  {
    id: "node-jaggampeta",
    name: "Jaggampeta (NH16)",
    district: "Kakinada",
    lat: 17.172,
    lng: 82.052,
    isHighwayJunction: true,
  },
  {
    id: "node-peddapuram",
    name: "Peddapuram (SH)",
    district: "Kakinada",
    lat: 17.078,
    lng: 82.138,
    isHighwayJunction: true,
  },
  {
    id: "node-kakinada",
    name: "Kakinada Port & City (NH216)",
    district: "Kakinada",
    lat: 16.989,
    lng: 82.247,
    isHighwayJunction: true,
  },
  {
    id: "node-samalkot",
    name: "Samalkot Junction",
    district: "Kakinada",
    lat: 17.051,
    lng: 82.172,
    isHighwayJunction: true,
  },
  {
    id: "node-rajahmundry",
    name: "Rajahmundry Central (NH16)",
    district: "East Godavari",
    lat: 17.0,
    lng: 81.804,
    isHighwayJunction: true,
  },
  {
    id: "node-dowleswaram",
    name: "Dowleswaram Barrage (NH16)",
    district: "East Godavari",
    lat: 16.942,
    lng: 81.776,
    isHighwayJunction: true,
  },
  {
    id: "node-kovvur",
    name: "Kovvur Godavari Bridge (NH16)",
    district: "East Godavari",
    lat: 17.014,
    lng: 81.728,
    isHighwayJunction: true,
  },
  {
    id: "node-ravulapalem",
    name: "Ravulapalem Junction (NH16/NH216)",
    district: "Dr. B.R. Ambedkar Konaseema",
    lat: 16.751,
    lng: 81.844,
    isHighwayJunction: true,
  },
  {
    id: "node-amalapuram",
    name: "Amalapuram Central (NH216)",
    district: "Dr. B.R. Ambedkar Konaseema",
    lat: 16.579,
    lng: 82.006,
    isHighwayJunction: true,
  },
  {
    id: "node-tanuku",
    name: "Tanuku (NH16)",
    district: "West Godavari",
    lat: 16.757,
    lng: 81.684,
    isHighwayJunction: true,
  },
  {
    id: "node-tadepalligudem",
    name: "Tadepalligudem (NH16)",
    district: "West Godavari",
    lat: 16.812,
    lng: 81.528,
    isHighwayJunction: true,
  },
  {
    id: "node-bhimavaram",
    name: "Bhimavaram Central (SH/NH216)",
    district: "West Godavari",
    lat: 16.545,
    lng: 81.521,
    isHighwayJunction: true,
  },
  {
    id: "node-narsapur",
    name: "Narsapur Coastal Hub (NH216)",
    district: "West Godavari",
    lat: 16.438,
    lng: 81.698,
    isHighwayJunction: true,
  },
  {
    id: "node-eluru",
    name: "Eluru Bypass (NH16)",
    district: "Eluru",
    lat: 16.711,
    lng: 81.095,
    isHighwayJunction: true,
  },
  {
    id: "node-hanuman-junction",
    name: "Hanuman Junction (NH16/NH221)",
    district: "Eluru",
    lat: 16.638,
    lng: 80.962,
    isHighwayJunction: true,
  },
  {
    id: "node-gannavaram",
    name: "Gannavaram Airport (NH16)",
    district: "Krishna",
    lat: 16.536,
    lng: 80.798,
    isHighwayJunction: true,
  },
  {
    id: "node-vijayawada",
    name: "Vijayawada City Core (NH16/NH65)",
    district: "NTR",
    lat: 16.506,
    lng: 80.648,
    isHighwayJunction: true,
  },
  {
    id: "node-ibrahimpatnam",
    name: "Ibrahimpatnam Junction (NH65)",
    district: "NTR",
    lat: 16.586,
    lng: 80.528,
    isHighwayJunction: true,
  },
  {
    id: "node-nandigama",
    name: "Nandigama (NH65)",
    district: "NTR",
    lat: 16.772,
    lng: 80.292,
    isHighwayJunction: true,
  },
  {
    id: "node-jaggaiahpet",
    name: "Jaggaiahpet Border (NH65)",
    district: "NTR",
    lat: 16.892,
    lng: 80.098,
    isHighwayJunction: true,
  },
  {
    id: "node-mangalagiri",
    name: "Mangalagiri AIIMS/Police HQ (NH16)",
    district: "Guntur",
    lat: 16.432,
    lng: 80.564,
    isHighwayJunction: true,
  },
  {
    id: "node-guntur",
    name: "Guntur City Central (NH16)",
    district: "Guntur",
    lat: 16.307,
    lng: 80.436,
    isHighwayJunction: true,
  },
  {
    id: "node-chilakaluripet",
    name: "Chilakaluripet Bypass (NH16)",
    district: "Palnadu",
    lat: 16.089,
    lng: 80.168,
    isHighwayJunction: true,
  },
  {
    id: "node-narasaraopet",
    name: "Narasaraopet (SH)",
    district: "Palnadu",
    lat: 16.236,
    lng: 80.049,
    isHighwayJunction: true,
  },
  {
    id: "node-macherla",
    name: "Macherla (NH565)",
    district: "Palnadu",
    lat: 16.478,
    lng: 79.298,
    isHighwayJunction: true,
  },
  {
    id: "node-medarametla",
    name: "Medarametla Junction (NH16)",
    district: "Bapatla",
    lat: 15.824,
    lng: 80.012,
    isHighwayJunction: true,
  },
  {
    id: "node-bapatla",
    name: "Bapatla Central (NH216)",
    district: "Bapatla",
    lat: 15.904,
    lng: 80.468,
    isHighwayJunction: true,
  },
  {
    id: "node-chirala",
    name: "Chirala Coastal (NH216)",
    district: "Bapatla",
    lat: 15.828,
    lng: 80.354,
    isHighwayJunction: true,
  },
  {
    id: "node-repalle",
    name: "Repalle (NH216)",
    district: "Bapatla",
    lat: 16.018,
    lng: 80.842,
    isHighwayJunction: true,
  },
  {
    id: "node-machilipatnam",
    name: "Machilipatnam Port (NH65/NH216)",
    district: "Krishna",
    lat: 16.188,
    lng: 81.139,
    isHighwayJunction: true,
  },
  {
    id: "node-vuyyuru",
    name: "Vuyyuru (NH65)",
    district: "Krishna",
    lat: 16.368,
    lng: 80.844,
    isHighwayJunction: true,
  },
  {
    id: "node-ongole",
    name: "Ongole Central (NH16)",
    district: "Prakasam",
    lat: 15.506,
    lng: 80.05,
    isHighwayJunction: true,
  },
  {
    id: "node-tanguturu",
    name: "Tanguturu (NH16)",
    district: "Prakasam",
    lat: 15.352,
    lng: 80.018,
    isHighwayJunction: false,
  },
  {
    id: "node-singarayakonda",
    name: "Singarayakonda (NH16)",
    district: "Prakasam",
    lat: 15.251,
    lng: 80.024,
    isHighwayJunction: true,
  },
  {
    id: "node-kavali",
    name: "Kavali (NH16)",
    district: "SPS Nellore",
    lat: 14.912,
    lng: 79.987,
    isHighwayJunction: true,
  },
  {
    id: "node-nellore",
    name: "Nellore City Central (NH16)",
    district: "SPS Nellore",
    lat: 14.443,
    lng: 79.987,
    isHighwayJunction: true,
  },
  {
    id: "node-gudur",
    name: "Gudur Junction (NH16)",
    district: "Tirupati",
    lat: 14.148,
    lng: 79.851,
    isHighwayJunction: true,
  },
  {
    id: "node-naidupeta",
    name: "Naidupeta Junction (NH16/NH71)",
    district: "Tirupati",
    lat: 13.912,
    lng: 79.902,
    isHighwayJunction: true,
  },
  {
    id: "node-sullurpeta",
    name: "Sullurpeta / ISRO Gateway (NH16)",
    district: "Tirupati",
    lat: 13.698,
    lng: 80.021,
    isHighwayJunction: true,
  },
  {
    id: "node-tada",
    name: "Tada Border (NH16)",
    district: "Tirupati",
    lat: 13.578,
    lng: 80.038,
    isHighwayJunction: true,
  },
  {
    id: "node-srikalahasti",
    name: "Srikalahasti (NH71)",
    district: "Tirupati",
    lat: 13.754,
    lng: 79.702,
    isHighwayJunction: true,
  },
  {
    id: "node-renigunta",
    name: "Renigunta Junction (NH71/NH716)",
    district: "Tirupati",
    lat: 13.648,
    lng: 79.518,
    isHighwayJunction: true,
  },
  {
    id: "node-tirupati",
    name: "Tirupati Central (NH71/NH716)",
    district: "Tirupati",
    lat: 13.629,
    lng: 79.419,
    isHighwayJunction: true,
  },
  {
    id: "node-chittoor",
    name: "Chittoor Central (NH40/NH69)",
    district: "Chittoor",
    lat: 13.217,
    lng: 79.1,
    isHighwayJunction: true,
  },
  {
    id: "node-palamaner",
    name: "Palamaner (NH69)",
    district: "Chittoor",
    lat: 13.201,
    lng: 78.751,
    isHighwayJunction: true,
  },
  {
    id: "node-kuppam",
    name: "Kuppam (SH)",
    district: "Chittoor",
    lat: 12.752,
    lng: 78.364,
    isHighwayJunction: false,
  },
  {
    id: "node-madanapalle",
    name: "Madanapalle (NH42)",
    district: "Annamayya",
    lat: 13.551,
    lng: 78.502,
    isHighwayJunction: true,
  },
  {
    id: "node-rayachoti",
    name: "Rayachoti Central (NH40)",
    district: "Annamayya",
    lat: 14.057,
    lng: 78.751,
    isHighwayJunction: true,
  },
  {
    id: "node-rajampet",
    name: "Rajampet (NH716)",
    district: "Annamayya",
    lat: 14.195,
    lng: 79.158,
    isHighwayJunction: true,
  },
  {
    id: "node-kodur",
    name: "Railway Kodur (NH716)",
    district: "Annamayya",
    lat: 13.952,
    lng: 79.351,
    isHighwayJunction: true,
  },
  {
    id: "node-kadapa",
    name: "Kadapa City Central (NH40/NH716)",
    district: "YSR (Kadapa)",
    lat: 14.467,
    lng: 78.824,
    isHighwayJunction: true,
  },
  {
    id: "node-mydukur",
    name: "Mydukur Junction (NH40/NH67)",
    district: "YSR (Kadapa)",
    lat: 14.851,
    lng: 78.718,
    isHighwayJunction: true,
  },
  {
    id: "node-proddatur",
    name: "Proddatur (NH67)",
    district: "YSR (Kadapa)",
    lat: 14.731,
    lng: 78.552,
    isHighwayJunction: true,
  },
  {
    id: "node-jammalamadugu",
    name: "Jammalamadugu / Gandikota (NH67)",
    district: "YSR (Kadapa)",
    lat: 14.848,
    lng: 78.391,
    isHighwayJunction: true,
  },
  {
    id: "node-allagadda",
    name: "Allagadda (NH40)",
    district: "Nandyal",
    lat: 15.132,
    lng: 78.512,
    isHighwayJunction: true,
  },
  {
    id: "node-nandyal",
    name: "Nandyal Central (NH40/NH544D)",
    district: "Nandyal",
    lat: 15.479,
    lng: 78.484,
    isHighwayJunction: true,
  },
  {
    id: "node-giddalur",
    name: "Giddalur (NH544D)",
    district: "Prakasam",
    lat: 15.378,
    lng: 78.924,
    isHighwayJunction: true,
  },
  {
    id: "node-markapur",
    name: "Markapur (NH565)",
    district: "Prakasam",
    lat: 15.735,
    lng: 79.278,
    isHighwayJunction: true,
  },
  {
    id: "node-orvakal",
    name: "Orvakal Airport (NH40)",
    district: "Kurnool",
    lat: 15.682,
    lng: 78.218,
    isHighwayJunction: true,
  },
  {
    id: "node-kurnool",
    name: "Kurnool City Central (NH44/NH40)",
    district: "Kurnool",
    lat: 15.828,
    lng: 78.037,
    isHighwayJunction: true,
  },
  {
    id: "node-dhone",
    name: "Dhone Junction (NH44)",
    district: "Nandyal",
    lat: 15.421,
    lng: 77.872,
    isHighwayJunction: true,
  },
  {
    id: "node-gooty",
    name: "Gooty Junction (NH44/NH67)",
    district: "Ananthapuramu",
    lat: 15.112,
    lng: 77.638,
    isHighwayJunction: true,
  },
  {
    id: "node-anantapur",
    name: "Anantapur City Central (NH44/NH42)",
    district: "Ananthapuramu",
    lat: 14.682,
    lng: 77.601,
    isHighwayJunction: true,
  },
  {
    id: "node-dharmavaram",
    name: "Dharmavaram (NH42)",
    district: "Sri Sathya Sai",
    lat: 14.412,
    lng: 77.721,
    isHighwayJunction: true,
  },
  {
    id: "node-puttaparthi",
    name: "Puttaparthi (SH)",
    district: "Sri Sathya Sai",
    lat: 14.167,
    lng: 77.812,
    isHighwayJunction: true,
  },
  {
    id: "node-penukonda",
    name: "Penukonda (NH44)",
    district: "Sri Sathya Sai",
    lat: 14.084,
    lng: 77.595,
    isHighwayJunction: true,
  },
  {
    id: "node-hindupur",
    name: "Hindupur (NH44)",
    district: "Sri Sathya Sai",
    lat: 13.829,
    lng: 77.492,
    isHighwayJunction: true,
  },
  {
    id: "node-adoni",
    name: "Adoni (SH)",
    district: "Kurnool",
    lat: 15.628,
    lng: 77.275,
    isHighwayJunction: true,
  },
  {
    id: "node-araku",
    name: "Araku Valley Hub (NH516E)",
    district: "Alluri Sitharama Raju",
    lat: 18.327,
    lng: 82.881,
    isHighwayJunction: true,
  },
  {
    id: "node-paderu",
    name: "Paderu Agency Hub (NH516E)",
    district: "Alluri Sitharama Raju",
    lat: 18.083,
    lng: 82.667,
    isHighwayJunction: true,
  },
  {
    id: "node-parvathipuram",
    name: "Parvathipuram Hub (NH26)",
    district: "Parvathipuram Manyam",
    lat: 18.783,
    lng: 83.433,
    isHighwayJunction: true,
  },
];

/**
 * Interconnected road segments with real road geometry tracing actual Andhra Pradesh National & State Highways.
 */
export const AP_ROAD_SEGMENTS: RoadSegment[] = [
  // NH16 Srikakulam to Visakhapatnam
  {
    id: "seg-nh16-ichchapuram-sompeta",
    fromNodeId: "node-ichchapuram",
    toNodeId: "node-sompeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.5,
    speedLimitKmh: 80,
    path: [
      { lat: 19.116, lng: 84.693 },
      { lat: 19.02, lng: 84.64 },
      { lat: 18.932, lng: 84.588 },
    ],
  },
  {
    id: "seg-nh16-sompeta-tekkali",
    fromNodeId: "node-sompeta",
    toNodeId: "node-tekkali",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 85,
    path: [
      { lat: 18.932, lng: 84.588 },
      { lat: 18.78, lng: 84.41 },
      { lat: 18.68, lng: 84.3 },
      { lat: 18.614, lng: 84.237 },
    ],
  },
  {
    id: "seg-nh16-tekkali-narasannapeta",
    fromNodeId: "node-tekkali",
    toNodeId: "node-narasannapeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 28.5,
    speedLimitKmh: 85,
    path: [
      { lat: 18.614, lng: 84.237 },
      { lat: 18.52, lng: 84.14 },
      { lat: 18.423, lng: 84.045 },
    ],
  },
  {
    id: "seg-nh16-narasannapeta-srikakulam",
    fromNodeId: "node-narasannapeta",
    toNodeId: "node-srikakulam",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 22.0,
    speedLimitKmh: 80,
    path: [
      { lat: 18.423, lng: 84.045 },
      { lat: 18.35, lng: 83.96 },
      { lat: 18.297, lng: 83.897 },
    ],
  },
  {
    id: "seg-nh16-srikakulam-ranasthalam",
    fromNodeId: "node-srikakulam",
    toNodeId: "node-ranasthalam",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 27.5,
    speedLimitKmh: 80,
    path: [
      { lat: 18.297, lng: 83.897 },
      { lat: 18.25, lng: 83.78 },
      { lat: 18.216, lng: 83.673 },
    ],
  },
  {
    id: "seg-nh16-ranasthalam-vizianagaram",
    fromNodeId: "node-ranasthalam",
    toNodeId: "node-vizianagaram",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 85,
    path: [
      { lat: 18.216, lng: 83.673 },
      { lat: 18.16, lng: 83.52 },
      { lat: 18.112, lng: 83.398 },
    ],
  },
  {
    id: "seg-nh16-vizianagaram-anandapuram",
    fromNodeId: "node-vizianagaram",
    toNodeId: "node-anandapuram",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 26.5,
    speedLimitKmh: 85,
    path: [
      { lat: 18.112, lng: 83.398 },
      { lat: 18.01, lng: 83.38 },
      { lat: 17.908, lng: 83.376 },
    ],
  },
  {
    id: "seg-nh16-anandapuram-madhurawada",
    fromNodeId: "node-anandapuram",
    toNodeId: "node-madhurawada",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 14.0,
    speedLimitKmh: 70,
    path: [
      { lat: 17.908, lng: 83.376 },
      { lat: 17.85, lng: 83.36 },
      { lat: 17.808, lng: 83.355 },
    ],
  },
  {
    id: "seg-nh16-madhurawada-visakhapatnam",
    fromNodeId: "node-madhurawada",
    toNodeId: "node-visakhapatnam",
    roadName: "NH16",
    roadType: "ARTERIAL",
    distanceKm: 18.5,
    speedLimitKmh: 55,
    path: [
      { lat: 17.808, lng: 83.355 },
      { lat: 17.74, lng: 83.31 },
      { lat: 17.687, lng: 83.218 },
    ],
  },
  {
    id: "seg-nh16-visakhapatnam-gajuwaka",
    fromNodeId: "node-visakhapatnam",
    toNodeId: "node-gajuwaka",
    roadName: "NH16",
    roadType: "ARTERIAL",
    distanceKm: 12.0,
    speedLimitKmh: 50,
    path: [
      { lat: 17.687, lng: 83.218 },
      { lat: 17.698, lng: 83.189 },
    ],
  },
  {
    id: "seg-nh16-gajuwaka-kurmannapalem",
    fromNodeId: "node-gajuwaka",
    toNodeId: "node-kurmannapalem",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 6.5,
    speedLimitKmh: 65,
    path: [
      { lat: 17.698, lng: 83.189 },
      { lat: 17.678, lng: 83.145 },
    ],
  },
  {
    id: "seg-nh16-kurmannapalem-anakapalli",
    fromNodeId: "node-kurmannapalem",
    toNodeId: "node-anakapalli",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 18.0,
    speedLimitKmh: 80,
    path: [
      { lat: 17.678, lng: 83.145 },
      { lat: 17.68, lng: 83.07 },
      { lat: 17.69, lng: 83.003 },
    ],
  },
  {
    id: "seg-nh16-anakapalli-yelamanchili",
    fromNodeId: "node-anakapalli",
    toNodeId: "node-yelamanchili",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 22.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.69, lng: 83.003 },
      { lat: 17.61, lng: 82.93 },
      { lat: 17.552, lng: 82.862 },
    ],
  },
  {
    id: "seg-nh16-yelamanchili-nakapalli",
    fromNodeId: "node-yelamanchili",
    toNodeId: "node-nakapalli",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 20.5,
    speedLimitKmh: 85,
    path: [
      { lat: 17.552, lng: 82.862 },
      { lat: 17.48, lng: 82.78 },
      { lat: 17.432, lng: 82.721 },
    ],
  },
  {
    id: "seg-nh16-nakapalli-payakaraopeta",
    fromNodeId: "node-nakapalli",
    toNodeId: "node-payakaraopeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 19.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.432, lng: 82.721 },
      { lat: 17.39, lng: 82.63 },
      { lat: 17.362, lng: 82.571 },
    ],
  },
  {
    id: "seg-nh16-payakaraopeta-tuni",
    fromNodeId: "node-payakaraopeta",
    toNodeId: "node-tuni",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 3.5,
    speedLimitKmh: 65,
    path: [
      { lat: 17.362, lng: 82.571 },
      { lat: 17.354, lng: 82.548 },
    ],
  },
  {
    id: "seg-nh16-tuni-annavaram",
    fromNodeId: "node-tuni",
    toNodeId: "node-annavaram",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 18.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.354, lng: 82.548 },
      { lat: 17.31, lng: 82.46 },
      { lat: 17.283, lng: 82.404 },
    ],
  },
  {
    id: "seg-nh16-annavaram-kathipudi",
    fromNodeId: "node-annavaram",
    toNodeId: "node-kathipudi",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 11.5,
    speedLimitKmh: 85,
    path: [
      { lat: 17.283, lng: 82.404 },
      { lat: 17.241, lng: 82.339 },
    ],
  },
  {
    id: "seg-nh16-kathipudi-jaggampeta",
    fromNodeId: "node-kathipudi",
    toNodeId: "node-jaggampeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.241, lng: 82.339 },
      { lat: 17.2, lng: 82.18 },
      { lat: 17.172, lng: 82.052 },
    ],
  },
  {
    id: "seg-nh16-jaggampeta-rajahmundry",
    fromNodeId: "node-jaggampeta",
    toNodeId: "node-rajahmundry",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 35.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.172, lng: 82.052 },
      { lat: 17.08, lng: 81.92 },
      { lat: 17.0, lng: 81.804 },
    ],
  },
  // Kakinada - NH216 Connectors
  {
    id: "seg-nh216-kathipudi-kakinada",
    fromNodeId: "node-kathipudi",
    toNodeId: "node-kakinada",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 38.0,
    speedLimitKmh: 75,
    path: [
      { lat: 17.241, lng: 82.339 },
      { lat: 17.12, lng: 82.28 },
      { lat: 16.989, lng: 82.247 },
    ],
  },
  {
    id: "seg-sh-kakinada-samalkot",
    fromNodeId: "node-kakinada",
    toNodeId: "node-samalkot",
    roadName: "ADB Road",
    roadType: "STATE_HIGHWAY",
    distanceKm: 14.5,
    speedLimitKmh: 65,
    path: [
      { lat: 16.989, lng: 82.247 },
      { lat: 17.051, lng: 82.172 },
    ],
  },
  {
    id: "seg-sh-samalkot-rajahmundry",
    fromNodeId: "node-samalkot",
    toNodeId: "node-rajahmundry",
    roadName: "SH42",
    roadType: "STATE_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 70,
    path: [
      { lat: 17.051, lng: 82.172 },
      { lat: 17.078, lng: 82.138 },
      { lat: 17.05, lng: 81.95 },
      { lat: 17.0, lng: 81.804 },
    ],
  },
  {
    id: "seg-nh216-kakinada-amalapuram",
    fromNodeId: "node-kakinada",
    toNodeId: "node-amalapuram",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 54.0,
    speedLimitKmh: 65,
    path: [
      { lat: 16.989, lng: 82.247 },
      { lat: 16.78, lng: 82.15 },
      { lat: 16.579, lng: 82.006 },
    ],
  },
  {
    id: "seg-nh216-amalapuram-ravulapalem",
    fromNodeId: "node-amalapuram",
    toNodeId: "node-ravulapalem",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 28.0,
    speedLimitKmh: 70,
    path: [
      { lat: 16.579, lng: 82.006 },
      { lat: 16.68, lng: 81.92 },
      { lat: 16.751, lng: 81.844 },
    ],
  },
  {
    id: "seg-nh16-rajahmundry-ravulapalem",
    fromNodeId: "node-rajahmundry",
    toNodeId: "node-ravulapalem",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 32.0,
    speedLimitKmh: 85,
    path: [
      { lat: 17.0, lng: 81.804 },
      { lat: 16.942, lng: 81.776 },
      { lat: 16.85, lng: 81.8 },
      { lat: 16.751, lng: 81.844 },
    ],
  },
  {
    id: "seg-nh16-ravulapalem-tanuku",
    fromNodeId: "node-ravulapalem",
    toNodeId: "node-tanuku",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.0,
    speedLimitKmh: 85,
    path: [
      { lat: 16.751, lng: 81.844 },
      { lat: 16.76, lng: 81.75 },
      { lat: 16.757, lng: 81.684 },
    ],
  },
  {
    id: "seg-nh16-tanuku-tadepalligudem",
    fromNodeId: "node-tanuku",
    toNodeId: "node-tadepalligudem",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 20.0,
    speedLimitKmh: 85,
    path: [
      { lat: 16.757, lng: 81.684 },
      { lat: 16.79, lng: 81.6 },
      { lat: 16.812, lng: 81.528 },
    ],
  },
  {
    id: "seg-sh-tanuku-bhimavaram",
    fromNodeId: "node-tanuku",
    toNodeId: "node-bhimavaram",
    roadName: "SH44",
    roadType: "STATE_HIGHWAY",
    distanceKm: 28.5,
    speedLimitKmh: 65,
    path: [
      { lat: 16.757, lng: 81.684 },
      { lat: 16.64, lng: 81.6 },
      { lat: 16.545, lng: 81.521 },
    ],
  },
  {
    id: "seg-nh216-bhimavaram-narsapur",
    fromNodeId: "node-bhimavaram",
    toNodeId: "node-narsapur",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.0,
    speedLimitKmh: 65,
    path: [
      { lat: 16.545, lng: 81.521 },
      { lat: 16.48, lng: 81.62 },
      { lat: 16.438, lng: 81.698 },
    ],
  },
  {
    id: "seg-nh16-tadepalligudem-eluru",
    fromNodeId: "node-tadepalligudem",
    toNodeId: "node-eluru",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.812, lng: 81.528 },
      { lat: 16.78, lng: 81.35 },
      { lat: 16.75, lng: 81.22 },
      { lat: 16.711, lng: 81.095 },
    ],
  },
  {
    id: "seg-nh16-eluru-hanuman-junction",
    fromNodeId: "node-eluru",
    toNodeId: "node-hanuman-junction",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 21.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.711, lng: 81.095 },
      { lat: 16.67, lng: 81.02 },
      { lat: 16.638, lng: 80.962 },
    ],
  },
  {
    id: "seg-nh16-hanuman-junction-gannavaram",
    fromNodeId: "node-hanuman-junction",
    toNodeId: "node-gannavaram",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 22.0,
    speedLimitKmh: 85,
    path: [
      { lat: 16.638, lng: 80.962 },
      { lat: 16.58, lng: 80.88 },
      { lat: 16.536, lng: 80.798 },
    ],
  },
  {
    id: "seg-nh16-gannavaram-vijayawada",
    fromNodeId: "node-gannavaram",
    toNodeId: "node-vijayawada",
    roadName: "NH16 / Benz Circle",
    roadType: "ARTERIAL",
    distanceKm: 18.0,
    speedLimitKmh: 60,
    path: [
      { lat: 16.536, lng: 80.798 },
      { lat: 16.515, lng: 80.72 },
      { lat: 16.506, lng: 80.648 },
    ],
  },
  // NH65 Vijayawada East-West Corridor
  {
    id: "seg-nh65-machilipatnam-vuyyuru",
    fromNodeId: "node-machilipatnam",
    toNodeId: "node-vuyyuru",
    roadName: "NH65",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 38.0,
    speedLimitKmh: 75,
    path: [
      { lat: 16.188, lng: 81.139 },
      { lat: 16.28, lng: 80.98 },
      { lat: 16.368, lng: 80.844 },
    ],
  },
  {
    id: "seg-nh65-vuyyuru-vijayawada",
    fromNodeId: "node-vuyyuru",
    toNodeId: "node-vijayawada",
    roadName: "NH65 (Bandar Road)",
    roadType: "ARTERIAL",
    distanceKm: 28.0,
    speedLimitKmh: 65,
    path: [
      { lat: 16.368, lng: 80.844 },
      { lat: 16.44, lng: 80.74 },
      { lat: 16.506, lng: 80.648 },
    ],
  },
  {
    id: "seg-nh65-vijayawada-ibrahimpatnam",
    fromNodeId: "node-vijayawada",
    toNodeId: "node-ibrahimpatnam",
    roadName: "NH65",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 16.0,
    speedLimitKmh: 70,
    path: [
      { lat: 16.506, lng: 80.648 },
      { lat: 16.54, lng: 80.58 },
      { lat: 16.586, lng: 80.528 },
    ],
  },
  {
    id: "seg-nh65-ibrahimpatnam-nandigama",
    fromNodeId: "node-ibrahimpatnam",
    toNodeId: "node-nandigama",
    roadName: "NH65",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 32.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.586, lng: 80.528 },
      { lat: 16.68, lng: 80.4 },
      { lat: 16.772, lng: 80.292 },
    ],
  },
  {
    id: "seg-nh65-nandigama-jaggaiahpet",
    fromNodeId: "node-nandigama",
    toNodeId: "node-jaggaiahpet",
    roadName: "NH65",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.772, lng: 80.292 },
      { lat: 16.83, lng: 80.18 },
      { lat: 16.892, lng: 80.098 },
    ],
  },
  // NH16 Vijayawada to Guntur & Ongole
  {
    id: "seg-nh16-vijayawada-mangalagiri",
    fromNodeId: "node-vijayawada",
    toNodeId: "node-mangalagiri",
    roadName: "NH16 (Prakasam Barrage Express)",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 14.0,
    speedLimitKmh: 80,
    path: [
      { lat: 16.506, lng: 80.648 },
      { lat: 16.48, lng: 80.6 },
      { lat: 16.432, lng: 80.564 },
    ],
  },
  {
    id: "seg-nh16-mangalagiri-guntur",
    fromNodeId: "node-mangalagiri",
    toNodeId: "node-guntur",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 18.0,
    speedLimitKmh: 85,
    path: [
      { lat: 16.432, lng: 80.564 },
      { lat: 16.37, lng: 80.5 },
      { lat: 16.307, lng: 80.436 },
    ],
  },
  {
    id: "seg-nh16-guntur-chilakaluripet",
    fromNodeId: "node-guntur",
    toNodeId: "node-chilakaluripet",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.307, lng: 80.436 },
      { lat: 16.2, lng: 80.3 },
      { lat: 16.089, lng: 80.168 },
    ],
  },
  {
    id: "seg-sh-guntur-narasaraopet",
    fromNodeId: "node-guntur",
    toNodeId: "node-narasaraopet",
    roadName: "SH45",
    roadType: "STATE_HIGHWAY",
    distanceKm: 46.0,
    speedLimitKmh: 75,
    path: [
      { lat: 16.307, lng: 80.436 },
      { lat: 16.27, lng: 80.22 },
      { lat: 16.236, lng: 80.049 },
    ],
  },
  {
    id: "seg-nh565-narasaraopet-macherla",
    fromNodeId: "node-narasaraopet",
    toNodeId: "node-macherla",
    roadName: "NH565",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 82.0,
    speedLimitKmh: 75,
    path: [
      { lat: 16.236, lng: 80.049 },
      { lat: 16.35, lng: 79.7 },
      { lat: 16.478, lng: 79.298 },
    ],
  },
  {
    id: "seg-nh16-chilakaluripet-medarametla",
    fromNodeId: "node-chilakaluripet",
    toNodeId: "node-medarametla",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 90,
    path: [
      { lat: 16.089, lng: 80.168 },
      { lat: 15.95, lng: 80.08 },
      { lat: 15.824, lng: 80.012 },
    ],
  },
  {
    id: "seg-nh16-medarametla-ongole",
    fromNodeId: "node-medarametla",
    toNodeId: "node-ongole",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 36.0,
    speedLimitKmh: 90,
    path: [
      { lat: 15.824, lng: 80.012 },
      { lat: 15.66, lng: 80.03 },
      { lat: 15.506, lng: 80.05 },
    ],
  },
  // Coastal Corridors Bapatla / Chirala
  {
    id: "seg-nh216-bapatla-chirala",
    fromNodeId: "node-bapatla",
    toNodeId: "node-chirala",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 18.0,
    speedLimitKmh: 70,
    path: [
      { lat: 15.904, lng: 80.468 },
      { lat: 15.85, lng: 80.4 },
      { lat: 15.828, lng: 80.354 },
    ],
  },
  {
    id: "seg-nh216-chirala-ongole",
    fromNodeId: "node-chirala",
    toNodeId: "node-ongole",
    roadName: "NH216",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 75,
    path: [
      { lat: 15.828, lng: 80.354 },
      { lat: 15.65, lng: 80.2 },
      { lat: 15.506, lng: 80.05 },
    ],
  },
  {
    id: "seg-sh-guntur-bapatla",
    fromNodeId: "node-guntur",
    toNodeId: "node-bapatla",
    roadName: "SH52",
    roadType: "STATE_HIGHWAY",
    distanceKm: 52.0,
    speedLimitKmh: 70,
    path: [
      { lat: 16.307, lng: 80.436 },
      { lat: 16.1, lng: 80.45 },
      { lat: 15.904, lng: 80.468 },
    ],
  },
  // NH16 Ongole to Nellore & Tada
  {
    id: "seg-nh16-ongole-singarayakonda",
    fromNodeId: "node-ongole",
    toNodeId: "node-singarayakonda",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 32.0,
    speedLimitKmh: 90,
    path: [
      { lat: 15.506, lng: 80.05 },
      { lat: 15.352, lng: 80.018 },
      { lat: 15.251, lng: 80.024 },
    ],
  },
  {
    id: "seg-nh16-singarayakonda-kavali",
    fromNodeId: "node-singarayakonda",
    toNodeId: "node-kavali",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 90,
    path: [
      { lat: 15.251, lng: 80.024 },
      { lat: 15.08, lng: 80.0 },
      { lat: 14.912, lng: 79.987 },
    ],
  },
  {
    id: "seg-nh16-kavali-nellore",
    fromNodeId: "node-kavali",
    toNodeId: "node-nellore",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 54.0,
    speedLimitKmh: 90,
    path: [
      { lat: 14.912, lng: 79.987 },
      { lat: 14.68, lng: 80.0 },
      { lat: 14.443, lng: 79.987 },
    ],
  },
  {
    id: "seg-nh16-nellore-gudur",
    fromNodeId: "node-nellore",
    toNodeId: "node-gudur",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 38.0,
    speedLimitKmh: 90,
    path: [
      { lat: 14.443, lng: 79.987 },
      { lat: 14.28, lng: 79.92 },
      { lat: 14.148, lng: 79.851 },
    ],
  },
  {
    id: "seg-nh16-gudur-naidupeta",
    fromNodeId: "node-gudur",
    toNodeId: "node-naidupeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 28.0,
    speedLimitKmh: 90,
    path: [
      { lat: 14.148, lng: 79.851 },
      { lat: 13.912, lng: 79.902 },
    ],
  },
  {
    id: "seg-nh16-naidupeta-sullurpeta",
    fromNodeId: "node-naidupeta",
    toNodeId: "node-sullurpeta",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 26.0,
    speedLimitKmh: 90,
    path: [
      { lat: 13.912, lng: 79.902 },
      { lat: 13.698, lng: 80.021 },
    ],
  },
  {
    id: "seg-nh16-sullurpeta-tada",
    fromNodeId: "node-sullurpeta",
    toNodeId: "node-tada",
    roadName: "NH16",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 16.0,
    speedLimitKmh: 90,
    path: [
      { lat: 13.698, lng: 80.021 },
      { lat: 13.578, lng: 80.038 },
    ],
  },
  // Tirupati / Chittoor / Rayalaseema Corridors (NH71, NH716, NH40, NH44)
  {
    id: "seg-nh71-naidupeta-srikalahasti",
    fromNodeId: "node-naidupeta",
    toNodeId: "node-srikalahasti",
    roadName: "NH71",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.912, lng: 79.902 },
      { lat: 13.82, lng: 79.8 },
      { lat: 13.754, lng: 79.702 },
    ],
  },
  {
    id: "seg-nh71-srikalahasti-renigunta",
    fromNodeId: "node-srikalahasti",
    toNodeId: "node-renigunta",
    roadName: "NH71",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.754, lng: 79.702 },
      { lat: 13.68, lng: 79.6 },
      { lat: 13.648, lng: 79.518 },
    ],
  },
  {
    id: "seg-nh71-renigunta-tirupati",
    fromNodeId: "node-renigunta",
    toNodeId: "node-tirupati",
    roadName: "NH71 / Bypass",
    roadType: "ARTERIAL",
    distanceKm: 12.0,
    speedLimitKmh: 65,
    path: [
      { lat: 13.648, lng: 79.518 },
      { lat: 13.629, lng: 79.419 },
    ],
  },
  {
    id: "seg-nh40-tirupati-chittoor",
    fromNodeId: "node-tirupati",
    toNodeId: "node-chittoor",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 68.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.629, lng: 79.419 },
      { lat: 13.45, lng: 79.25 },
      { lat: 13.217, lng: 79.1 },
    ],
  },
  {
    id: "seg-nh69-chittoor-palamaner",
    fromNodeId: "node-chittoor",
    toNodeId: "node-palamaner",
    roadName: "NH69",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.217, lng: 79.1 },
      { lat: 13.201, lng: 78.751 },
    ],
  },
  {
    id: "seg-sh-palamaner-kuppam",
    fromNodeId: "node-palamaner",
    toNodeId: "node-kuppam",
    roadName: "SH60",
    roadType: "STATE_HIGHWAY",
    distanceKm: 64.0,
    speedLimitKmh: 65,
    path: [
      { lat: 13.201, lng: 78.751 },
      { lat: 12.98, lng: 78.52 },
      { lat: 12.752, lng: 78.364 },
    ],
  },
  {
    id: "seg-nh42-palamaner-madanapalle",
    fromNodeId: "node-palamaner",
    toNodeId: "node-madanapalle",
    roadName: "NH42",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 75,
    path: [
      { lat: 13.201, lng: 78.751 },
      { lat: 13.38, lng: 78.6 },
      { lat: 13.551, lng: 78.502 },
    ],
  },
  {
    id: "seg-nh40-chittoor-rayachoti",
    fromNodeId: "node-chittoor",
    toNodeId: "node-rayachoti",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 102.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.217, lng: 79.1 },
      { lat: 13.68, lng: 78.95 },
      { lat: 14.057, lng: 78.751 },
    ],
  },
  {
    id: "seg-nh716-tirupati-kodur",
    fromNodeId: "node-tirupati",
    toNodeId: "node-kodur",
    roadName: "NH716",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 46.0,
    speedLimitKmh: 80,
    path: [
      { lat: 13.629, lng: 79.419 },
      { lat: 13.8, lng: 79.38 },
      { lat: 13.952, lng: 79.351 },
    ],
  },
  {
    id: "seg-nh716-kodur-rajampet",
    fromNodeId: "node-kodur",
    toNodeId: "node-rajampet",
    roadName: "NH716",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 85,
    path: [
      { lat: 13.952, lng: 79.351 },
      { lat: 14.08, lng: 79.25 },
      { lat: 14.195, lng: 79.158 },
    ],
  },
  {
    id: "seg-nh716-rajampet-kadapa",
    fromNodeId: "node-rajampet",
    toNodeId: "node-kadapa",
    roadName: "NH716",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 52.0,
    speedLimitKmh: 85,
    path: [
      { lat: 14.195, lng: 79.158 },
      { lat: 14.35, lng: 79.02 },
      { lat: 14.467, lng: 78.824 },
    ],
  },
  {
    id: "seg-nh40-rayachoti-kadapa",
    fromNodeId: "node-rayachoti",
    toNodeId: "node-kadapa",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 54.0,
    speedLimitKmh: 80,
    path: [
      { lat: 14.057, lng: 78.751 },
      { lat: 14.28, lng: 78.79 },
      { lat: 14.467, lng: 78.824 },
    ],
  },
  {
    id: "seg-nh40-kadapa-mydukur",
    fromNodeId: "node-kadapa",
    toNodeId: "node-mydukur",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 44.0,
    speedLimitKmh: 85,
    path: [
      { lat: 14.467, lng: 78.824 },
      { lat: 14.65, lng: 78.76 },
      { lat: 14.851, lng: 78.718 },
    ],
  },
  {
    id: "seg-nh67-mydukur-proddatur",
    fromNodeId: "node-mydukur",
    toNodeId: "node-proddatur",
    roadName: "NH67",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 22.0,
    speedLimitKmh: 75,
    path: [
      { lat: 14.851, lng: 78.718 },
      { lat: 14.731, lng: 78.552 },
    ],
  },
  {
    id: "seg-nh67-proddatur-jammalamadugu",
    fromNodeId: "node-proddatur",
    toNodeId: "node-jammalamadugu",
    roadName: "NH67",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 22.0,
    speedLimitKmh: 75,
    path: [
      { lat: 14.731, lng: 78.552 },
      { lat: 14.848, lng: 78.391 },
    ],
  },
  {
    id: "seg-nh40-mydukur-allagadda",
    fromNodeId: "node-mydukur",
    toNodeId: "node-allagadda",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 85,
    path: [
      { lat: 14.851, lng: 78.718 },
      { lat: 15.0, lng: 78.6 },
      { lat: 15.132, lng: 78.512 },
    ],
  },
  {
    id: "seg-nh40-allagadda-nandyal",
    fromNodeId: "node-allagadda",
    toNodeId: "node-nandyal",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 44.0,
    speedLimitKmh: 85,
    path: [
      { lat: 15.132, lng: 78.512 },
      { lat: 15.3, lng: 78.49 },
      { lat: 15.479, lng: 78.484 },
    ],
  },
  {
    id: "seg-nh544d-nandyal-giddalur",
    fromNodeId: "node-nandyal",
    toNodeId: "node-giddalur",
    roadName: "NH544D",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 56.0,
    speedLimitKmh: 75,
    path: [
      { lat: 15.479, lng: 78.484 },
      { lat: 15.4, lng: 78.72 },
      { lat: 15.378, lng: 78.924 },
    ],
  },
  {
    id: "seg-nh544d-giddalur-markapur",
    fromNodeId: "node-giddalur",
    toNodeId: "node-markapur",
    roadName: "NH544D",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 52.0,
    speedLimitKmh: 75,
    path: [
      { lat: 15.378, lng: 78.924 },
      { lat: 15.58, lng: 79.12 },
      { lat: 15.735, lng: 79.278 },
    ],
  },
  {
    id: "seg-nh40-nandyal-orvakal",
    fromNodeId: "node-nandyal",
    toNodeId: "node-orvakal",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 85,
    path: [
      { lat: 15.479, lng: 78.484 },
      { lat: 15.6, lng: 78.34 },
      { lat: 15.682, lng: 78.218 },
    ],
  },
  {
    id: "seg-nh40-orvakal-kurnool",
    fromNodeId: "node-orvakal",
    toNodeId: "node-kurnool",
    roadName: "NH40",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 24.0,
    speedLimitKmh: 80,
    path: [
      { lat: 15.682, lng: 78.218 },
      { lat: 15.76, lng: 78.11 },
      { lat: 15.828, lng: 78.037 },
    ],
  },
  // NH44 Kurnool to Anantapur & Bengaluru corridor
  {
    id: "seg-nh44-kurnool-dhone",
    fromNodeId: "node-kurnool",
    toNodeId: "node-dhone",
    roadName: "NH44",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 52.0,
    speedLimitKmh: 95,
    path: [
      { lat: 15.828, lng: 78.037 },
      { lat: 15.62, lng: 77.94 },
      { lat: 15.421, lng: 77.872 },
    ],
  },
  {
    id: "seg-nh44-dhone-gooty",
    fromNodeId: "node-dhone",
    toNodeId: "node-gooty",
    roadName: "NH44",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 95,
    path: [
      { lat: 15.421, lng: 77.872 },
      { lat: 15.26, lng: 77.74 },
      { lat: 15.112, lng: 77.638 },
    ],
  },
  {
    id: "seg-nh44-gooty-anantapur",
    fromNodeId: "node-gooty",
    toNodeId: "node-anantapur",
    roadName: "NH44",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 56.0,
    speedLimitKmh: 95,
    path: [
      { lat: 15.112, lng: 77.638 },
      { lat: 14.88, lng: 77.61 },
      { lat: 14.682, lng: 77.601 },
    ],
  },
  {
    id: "seg-nh42-anantapur-dharmavaram",
    fromNodeId: "node-anantapur",
    toNodeId: "node-dharmavaram",
    roadName: "NH42",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 42.0,
    speedLimitKmh: 80,
    path: [
      { lat: 14.682, lng: 77.601 },
      { lat: 14.54, lng: 77.68 },
      { lat: 14.412, lng: 77.721 },
    ],
  },
  {
    id: "seg-sh-dharmavaram-puttaparthi",
    fromNodeId: "node-dharmavaram",
    toNodeId: "node-puttaparthi",
    roadName: "SH55",
    roadType: "STATE_HIGHWAY",
    distanceKm: 34.0,
    speedLimitKmh: 70,
    path: [
      { lat: 14.412, lng: 77.721 },
      { lat: 14.28, lng: 77.76 },
      { lat: 14.167, lng: 77.812 },
    ],
  },
  {
    id: "seg-nh44-anantapur-penukonda",
    fromNodeId: "node-anantapur",
    toNodeId: "node-penukonda",
    roadName: "NH44",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 72.0,
    speedLimitKmh: 95,
    path: [
      { lat: 14.682, lng: 77.601 },
      { lat: 14.36, lng: 77.6 },
      { lat: 14.084, lng: 77.595 },
    ],
  },
  {
    id: "seg-nh44-penukonda-hindupur",
    fromNodeId: "node-penukonda",
    toNodeId: "node-hindupur",
    roadName: "NH44",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 36.0,
    speedLimitKmh: 90,
    path: [
      { lat: 14.084, lng: 77.595 },
      { lat: 13.95, lng: 77.53 },
      { lat: 13.829, lng: 77.492 },
    ],
  },
  // Hill & Agency Corridors (Araku, Paderu, Parvathipuram)
  {
    id: "seg-nh516e-anandapuram-araku",
    fromNodeId: "node-anandapuram",
    toNodeId: "node-araku",
    roadName: "NH516E (Ghat Road)",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 98.0,
    speedLimitKmh: 50,
    path: [
      { lat: 17.908, lng: 83.376 },
      { lat: 18.05, lng: 83.15 },
      { lat: 18.2, lng: 82.98 },
      { lat: 18.327, lng: 82.881 },
    ],
  },
  {
    id: "seg-sh-araku-paderu",
    fromNodeId: "node-araku",
    toNodeId: "node-paderu",
    roadName: "SH38 (Agency Highway)",
    roadType: "STATE_HIGHWAY",
    distanceKm: 48.0,
    speedLimitKmh: 45,
    path: [
      { lat: 18.327, lng: 82.881 },
      { lat: 18.2, lng: 82.78 },
      { lat: 18.083, lng: 82.667 },
    ],
  },
  {
    id: "seg-sh-paderu-anakapalli",
    fromNodeId: "node-paderu",
    toNodeId: "node-anakapalli",
    roadName: "SH38",
    roadType: "STATE_HIGHWAY",
    distanceKm: 64.0,
    speedLimitKmh: 50,
    path: [
      { lat: 18.083, lng: 82.667 },
      { lat: 17.88, lng: 82.84 },
      { lat: 17.69, lng: 83.003 },
    ],
  },
  {
    id: "seg-nh26-vizianagaram-parvathipuram",
    fromNodeId: "node-vizianagaram",
    toNodeId: "node-parvathipuram",
    roadName: "NH26",
    roadType: "NATIONAL_HIGHWAY",
    distanceKm: 78.0,
    speedLimitKmh: 75,
    path: [
      { lat: 18.112, lng: 83.398 },
      { lat: 18.42, lng: 83.42 },
      { lat: 18.65, lng: 83.43 },
      { lat: 18.783, lng: 83.433 },
    ],
  },
];

/**
 * Spatial lookup finding the closest road node for any GPS point in Andhra Pradesh.
 */
export function findNearestRoadNode(point: LatLng): RoadNode {
  let bestNode = AP_ROAD_NODES[0]!;
  let bestDist = haversineKm(point, { lat: bestNode.lat, lng: bestNode.lng });

  for (let i = 1; i < AP_ROAD_NODES.length; i++) {
    const node = AP_ROAD_NODES[i]!;
    const dist = haversineKm(point, { lat: node.lat, lng: node.lng });
    if (dist < bestDist) {
      bestDist = dist;
      bestNode = node;
    }
  }

  return bestNode;
}
